class BaseAgent:
    def reset(self, initial_state) -> None: ...
    def observe(self, obs) -> None: ...
    def act(self) -> Action  # Action is e.g. {'asset': 'SPY', 'type': 'target', 'target_shares': 100}
    def on_fill(self, fill_info) -> None: ...
